language: objective-c
osx_image: xcode7.2
env:
  global:
  - PROJECT=TBSwiftExtensions/TBSwiftExtensionsDemo.xcodeproj
  - IOS_SCHEME="TBSwiftExtensionsDemoIOS"
  - OSX_SCHEME="TBSwiftExtensionDemoOSX"
  - TVOS_SCHEME="TBSwiftExtensionsTVOS"
  - IOS_SDK=iphonesimulator9.2
  - OSX_SDK=macosx10.11
  - TVOS_SDK=appletvsimulator9.1
  matrix:
  - DESTINATION="OS=8.1,name=iPhone 4S"        SCHEME="$IOS_SCHEME"   SDK="$IOS_SDK"   RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="YES"
  - DESTINATION="OS=8.2,name=iPhone 5"         SCHEME="$IOS_SCHEME"   SDK="$IOS_SDK"   RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="NO"
  - DESTINATION="OS=8.3,name=iPhone 5S"        SCHEME="$IOS_SCHEME"   SDK="$IOS_SDK"   RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="NO"
  - DESTINATION="OS=8.4,name=iPhone 6"         SCHEME="$IOS_SCHEME"   SDK="$IOS_SDK"   RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="NO"
  - DESTINATION="OS=9.0,name=iPhone 6 Plus"    SCHEME="$IOS_SCHEME"   SDK="$IOS_SDK"   RUN_TESTS="NO"  BUILD_EXAMPLE="YES" POD_LINT="NO"
  - DESTINATION="OS=9.1,name=iPhone 6S"        SCHEME="$IOS_SCHEME"   SDK="$IOS_SDK"   RUN_TESTS="NO"  BUILD_EXAMPLE="YES" POD_LINT="NO" 
  - DESTINATION="OS=9.2,name=iPhone 6S Plus"   SCHEME="$IOS_SCHEME"   SDK="$IOS_SDK"   RUN_TESTS="NO"  BUILD_EXAMPLE="YES" POD_LINT="NO" 
  - DESTINATION="arch=x86_64"                  SCHEME="$OSX_SCHEME"   SDK="$OSX_SDK"   RUN_TESTS="NO"  BUILD_EXAMPLE="YES" POD_LINT="NO"
  - DESTINATION="OS=9.1,name=Apple TV 1080p"   SCHEME="$TVOS_SCHEME"  SDK="$TVOS_SDK"  RUN_TESTS="NO"  BUILD_EXAMPLE="YES" POD_LINT="NO"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    fi
  
  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi